version: "3.4"

services:
  db:
    image: postgres
    restart: always
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "5433:5432"
    volumes:
      - ./infrastracture/init.sql:/docker-entrypoint-initdb.d/init.sql
