FROM node:lts-alpine AS base

ENV NODE_ENV production

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm

FROM base AS prod-deps
RUN pnpm install --prod --frozen-lockfile

FROM base AS build
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm run build

FROM node:lts-alpine AS final

WORKDIR /app

COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/server.js ./server.js
EXPOSE 3000

CMD [ "pnpm", "start" ]